// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wellness_USC.Models;

namespace Wellness_USC.Migrations.ClaseDb
{
    [DbContext(typeof(ClaseDbContext))]
    [Migration("20201030093619_ClaseDb")]
    partial class ClaseDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("Wellness_USC.Models.Clase", b =>
                {
                    b.Property<int>("Id_Clase")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id_Horario")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id_Profesores")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<int>("cantidad")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_Clase");

                    b.HasIndex("Id");

                    b.HasIndex("Id_Horario");

                    b.HasIndex("Id_Profesores");

                    b.ToTable("Clase");
                });

            modelBuilder.Entity("Wellness_USC.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("Wellness_USC.Models.Horario", b =>
                {
                    b.Property<int>("Id_Horario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("release_date")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_Horario");

                    b.ToTable("Horario");
                });

            modelBuilder.Entity("Wellness_USC.Models.Profesores", b =>
                {
                    b.Property<int>("Id_Profesores")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apell")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageNameP")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_Profesores");

                    b.ToTable("Profesores");
                });

            modelBuilder.Entity("Wellness_USC.Models.Clase", b =>
                {
                    b.HasOne("Wellness_USC.Models.Course", "Courses")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wellness_USC.Models.Horario", "Horarios")
                        .WithMany("Clase")
                        .HasForeignKey("Id_Horario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wellness_USC.Models.Profesores", "Profesoress")
                        .WithMany("Clase")
                        .HasForeignKey("Id_Profesores")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
